DROP TABLE IF EXISTS users,
follows,
articles,
tags,
article_tags,
article_favs,
comments;
DROP INDEX IF EXISTS users_username_idx,
users_email_idx,
follows_follower_id_idx,
follows_followee_id_idx,
articles_slug_idx,
articles_author_id_idx,
tags_name_idx,
article_tags_article_id_idx,
article_tags_tag_id_idx,
article_favs_article_id_idx,
article_favs_user_id_idx,
comments_author_id_idx,
comments_article_id_idx;